# 足場として許可するブロック
# このブロックの上では死なない
allowed-blocks:
- OAK_LOG
- SPRUCE_LOG
- BIRCH_LOG
- JUNGLE_LOG
- ACACIA_LOG
- DARK_OAK_LOG
- MANGROVE_LOG
- CHERRY_LOG
- BAMBOO_BLOCK
- STRIPPED_OAK_LOG
- STRIPPED_SPRUCE_LOG
- STRIPPED_BIRCH_LOG
- STRIPPED_JUNGLE_LOG
- STRIPPED_ACACIA_LOG
- STRIPPED_DARK_OAK_LOG
- STRIPPED_MANGROVE_LOG
- STRIPPED_CHERRY_LOG
- STRIPPED_BAMBOO_BLOCK
- OAK_PLANKS
- SPRUCE_PLANKS
- BIRCH_PLANKS
- JUNGLE_PLANKS
- ACACIA_PLANKS
- DARK_OAK_PLANKS
- MANGROVE_PLANKS
- CHERRY_PLANKS
- BAMBOO_PLANKS
- OAK_SLAB
- SPRUCE_SLAB
- BIRCH_SLAB
- JUNGLE_SLAB
- ACACIA_SLAB
- DARK_OAK_SLAB
- MANGROVE_SLAB
- CHERRY_SLAB
- BAMBOO_SLAB
- OAK_WOOD
- SPRUCE_WOOD
- BIRCH_WOOD
- JUNGLE_WOOD
- ACACIA_WOOD
- DARK_OAK_WOOD
- MANGROVE_WOOD
- CHERRY_WOOD
- BAMBOO_MOSAIC
- STRIPPED_OAK_WOOD
- STRIPPED_SPRUCE_WOOD
- STRIPPED_BIRCH_WOOD
- STRIPPED_JUNGLE_WOOD
- STRIPPED_ACACIA_WOOD
- STRIPPED_DARK_OAK_WOOD
- STRIPPED_MANGROVE_WOOD
- STRIPPED_CHERRY_WOOD
- OAK_STAIRS
- SPRUCE_STAIRS
- BIRCH_STAIRS
- JUNGLE_STAIRS
- ACACIA_STAIRS
- DARK_OAK_STAIRS
- MANGROVE_STAIRS
- CHERRY_STAIRS
- BAMBOO_STAIRS

enabled: false # false にすると無効化される

messages:
  death: '&c木以外を踏んだので死亡しました。'
  reload: '&a設定が正常にリロードされました!'
  help: '&b/blockrestrictor reload を使用して設定をリロードしてください。'
  enabled: '&aブロック制限が有効になりました。'
  disabled: '&cブロック制限が無効になりました。'
